#!/bin/bash
clear
# warna
tebal='\033[1;1m'
merah='\033[1;31m'
hijau='\033[1;32m'
kuning='\033[1;33m'
biru='\033[1;34m'
mgnt='\033[1;35m'
cyan='\033[1;36m'
NC='\e[0m'
bg='\e[41m'
lebar=40
myip=$(curl -sS ipv4.icanhazip.com)
penyamaan() {
    lebar_judul=${#judul}
    peluasan=$(( (lebar - lebar_judul) /2 -1 ))
    padding=""
    for ((i=0; i<peluasan; i++)); do
        padding+=" "
    done
}
cetak_judul() {
    printf "${cyan}%s${NC}${bg}%s${tebal}%s%s${NC}${cyan}%s%s\n" "║" "$padding" "$judul" "$padding" "║"
}
cetak() {
lebarjudul=${#judul}
if (( lebarjudul % 2 == 1 )); then
    printf "${cyan}%s${warna}%s%s%s${NC}${cyan}%s%s\n" "║" "$padding" "$judul" "$padding" " " "║"
else
    printf "${cyan}%s${warna}%s%s%s${NC}${cyan}%s%s\n" "║" "$padding" "$judul" "$padding" "║"
fi
}
judul1() {
    warna="${tebal}${merah}"
    judul="PERIZINAN DILARANG"
    penyamaan
}
# ip
judul2() {
    warna="${NC}"
    judul="IP KAMU : $myip"
    penyamaan
}
judul3() {
    warna="${merah}"
    judul="Tidak mendapatkan izin"
    penyamaan
}
judul4() {
    warna="${NC}"
    judul="Silahkan hubungi Admin"
    penyamaan
}
judul5() {
    warna="${NC}"
    judul="Telegram : @alawivpn"
    penyamaan
}
echo -e "$cyan╔══════════════════════════════════════╗${NC}"
judul1
cetak_judul
echo -e "$cyan╚══════════════════════════════════════╝${NC}"
echo -e "$cyan╔══════════════════════════════════════╗${NC}"
judul2
cetak
judul3
cetak
judul4
cetak
judul5
cetak
echo -e "$cyan╚══════════════════════════════════════╝${NC}"
exit 0
